package com.wfc.test6.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTERPRISE.
 */
public class Enterprise {

    private Long id;
    private String fullName;
    private String shortName;
    private java.util.Date createTime;

    public Enterprise() {
    }

    public Enterprise(Long id) {
        this.id = id;
    }

    public Enterprise(Long id, String fullName, String shortName, java.util.Date createTime) {
        this.id = id;
        this.fullName = fullName;
        this.shortName = shortName;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

}
