package com.wfc.test4.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JOB.
 */
public class Job {

    private Long id;
    private String position;
    private String position1;
    private String jobName;
    private java.util.Date createTime;

    public Job() {
    }

    public Job(Long id) {
        this.id = id;
    }

    public Job(Long id, String position, String position1, String jobName, java.util.Date createTime) {
        this.id = id;
        this.position = position;
        this.position1 = position1;
        this.jobName = jobName;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getPosition1() {
        return position1;
    }

    public void setPosition1(String position1) {
        this.position1 = position1;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

}
