package com.wfc.test4.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wfc.test4.bean.User;
import com.wfc.test4.bean.Enterprise;
import com.wfc.test4.bean.Job;

import com.wfc.test4.dao.UserDao;
import com.wfc.test4.dao.EnterpriseDao;
import com.wfc.test4.dao.JobDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig enterpriseDaoConfig;
    private final DaoConfig jobDaoConfig;

    private final UserDao userDao;
    private final EnterpriseDao enterpriseDao;
    private final JobDao jobDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        enterpriseDaoConfig = daoConfigMap.get(EnterpriseDao.class).clone();
        enterpriseDaoConfig.initIdentityScope(type);

        jobDaoConfig = daoConfigMap.get(JobDao.class).clone();
        jobDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        enterpriseDao = new EnterpriseDao(enterpriseDaoConfig, this);
        jobDao = new JobDao(jobDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Enterprise.class, enterpriseDao);
        registerDao(Job.class, jobDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        enterpriseDaoConfig.getIdentityScope().clear();
        jobDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public EnterpriseDao getEnterpriseDao() {
        return enterpriseDao;
    }

    public JobDao getJobDao() {
        return jobDao;
    }

}
